AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-serverless-todo-workshop
  Full stack To-Do app with single-table DynamoDB design

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Ref TodoTable

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref AWS::StackName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TodoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_tasks.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref TodoApi
            Path: /tasks
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create_task.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref TodoApi
            Path: /tasks
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable

  GetTaskByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_task.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref TodoApi
            Path: /tasks/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update_task.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref TodoApi
            Path: /tasks/{id}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete_task.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref TodoApi
            Path: /tasks/{id}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_categories.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref TodoApi
            Path: /categories
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebsiteOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref WebsiteOAC
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  TableName:
    Description: DynamoDB table name
    Value: !Ref TodoTable
  CloudFrontUrl:
    Description: CloudFront URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  WebsiteBucketName:
    Description: S3 bucket for frontend files
    Value: !Ref WebsiteBucket